### ISSUE TITLE
Internationalizations support for multi language

### ISSUE THREAD

**Issue by StErMi** [dobarkod/cookie-banner#19]
Hi is there a way to pass to this script a variable body message and "Learn More"?
We need to provide this feature for different languages.

Thank you very much

**Comment by zytzagoo** [comment]
Might be a bit late, but for anyone else that might land here from Google or similar, this is/was working/supported out-of-the-box:

https://github.com/dobarkod/cookie-banner#options

The markup ends up being something like this for Italian (via Google Translate):
```html
<script id="cookiebanner" src="..." data-message="Utilizziamo i cookie per migliorare la vostra esperienza. Continuando a visitare questo sito l'utente accetta di utilizzare i cookie." data-linkmsg="saperne di più"></script>
```

Or like this for German (also via Google Translate):
```html
<script id="cookiebanner" src="..." data-message="Wir verwenden Cookies, um Ihre Erfahrungen zu verbessern. Durch die fortgesetzte dieser Website erklären Sie sich mit der Verwendung von Cookies zu besuchen." data-linkmsg="Erfahren Sie mehr"></script>
```
etc...

**Comment by facundofarias** [comment]
Right. That's what we are doing, just setting the data-message depending on the language. 
:+1:
