### ISSUE TITLE
Expiration

### ISSUE THREAD

**Issue by peterampazzo** [dobarkod/cookie-banner#23]
How can I set the inspiration up to 24 hours?

**Comment by zytzagoo** [comment]
Depends on the way you invoke/create it. This should work as a rough example:

```html
<script>
function cookie_expiry_callback() {
    return 86400; // 1 day (24 hours in seconds)
}
</script>

<script type="text/javascript" id="cookiebanner"
    src="//cookiebanner.eu/js/cookiebanner.js"
    ...
    data-expires="cookie_expiry_callback">
</script>
```

If you're creating a `new Cookiebanner()` yourself then just set the `expires` option.

Reading through (and running, potentially) the [tests sources](https://github.com/dobarkod/cookie-banner/blob/master/tests/tests.js) might also help.
