### ISSUE TITLE
data-text-align not work

### ISSUE THREAD

**Issue by distriker** [dobarkod/cookie-banner#25]
Hi @dobarkod,
I'm using your script, powerful and easy. But I am having a problem, I am trying center the text with data-text-align, but it don't work, the text continue align on the left. Here is the code that I build:
```html
<script type="text/javascript" id="cookiebanner"
	data-height="50px" data-bg="#22313F"
	data-message="Siento interrumpir tu navegación, pero me veo en la obligación de avisarte
	de que en este sitio web se usan cookies para mejorar tu experiencia (¡aunque muy pocas).
	Si continúas navegando estarás aceptando esto."
	data-text-align="right" data-linkmsg="¡Infórmate sobre las cookies!"
  src="http://cookiebanner.eu/js/cookiebanner.min.js"></script>
```
Everything works correct, except that attribute. [Here you have a fiddle](https://jsfiddle.net/IvanHerCaz/zja3uhre/) like it appears to me: on the left.

**Comment by zytzagoo** [comment]
Looks like the file up on http://cookiebanner.eu/js/cookiebanner.min.js is an older version (no mention of that option in that file) :/

Grab the master (latest) version and minify it yourself (at least until the version deployed on cookiebanneru.eu is updated).

**Comment by senko** [comment]
Yep, @zytzagoo is correct, I haven't uploaded the latest master to it yet, sorry!

**Comment by distriker** [comment]
Thank you so much for your help @zytzagoo and @senko!. I didn't notice that it was an older version. Now is everything correct!

Regards, *Iván*
