### ISSUE TITLE
Create bower package

### ISSUE THREAD

**Issue by alex88** [dobarkod/cookie-banner#27]
What about creating a bower package so users can include and host the file themselves along their project?

**Comment by 3oheme** [comment]
Hi @alex88 

Even if there's no bower package already created, you can use bower with a public Github account. For example, you can use bower to install the cookie banner with the following `bower.json` file (please notice I'm just showing an excerpt):

```
{
  "name": "YourProjectName",
  ...
  "dependencies": {
    "cookiebanner": "git@github.com:dobarkod/cookie-banner.git#master"
  },
}
```

Cheers!
