### ISSUE TITLE
moreinfo not working

### ISSUE THREAD

**Issue by justfalias** [dobarkod/cookie-banner#29]
Hi there,

I'm trying to use moreinfo parameter but it's not working. Others like data-message or data-linkmsg are working fine. Any clue?

Thanks in advance

**Comment by zytzagoo** [comment]
Hi, can you create a jsfiddle or provide a link that demonstrates the issue? 

Maybe there's something specific to the value of that option that you're trying to set that's causing it to fail, hard to say without more details...

**Comment by justfalias** [comment]
I created a jsfiddle but it's not working because I can't add the external resource because the URL is not https. Anyways here it is:

https://jsfiddle.net/ezq9kv4y/

**Comment by zytzagoo** [comment]
Yeah, options set via data attributes need their name to be prefixed with `data-` in HTML.
Updated fiddle that works as expected: https://jsfiddle.net/ezq9kv4y/1/

**Comment by justfalias** [comment]
Thanks a lot! Now everything it's working fine, it was an easy error to solve but in the documentation I only read moreinfo without data prefix.
