### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by mbifulco** [dobarkod/cookie-banner#30]
Hi - is there a recommendation for how to include the copyright/licensing for this in source?  I'm incorporating it into a fork of Open EdX that my company is using, and I want to make sure we give credit where it's due.  The copyright on your readme.md suggests that it  ["shall be included in all copies or substantial portions of the Software."](https://github.com/dobarkod/cookie-banner/blob/master/README.md#license)

Yet it isn't included in the .js file.  Should it perhaps be added there?

**Comment by senko** [comment]
Thanks @mbifulco for the ping - yeah, it should be in the source file as well. I've just added it there in https://github.com/dobarkod/cookie-banner/pull/31

Thanks!

**Comment by mbifulco** [comment]
Hey great, thanks @senko!
