### ISSUE TITLE
Android 

### ISSUE THREAD

**Issue by mxdpeep** [dobarkod/cookie-banner#32]
doesn't work, no banner 

Chrome for Android, OS 4.4.4 KitKat, Vodafone Smart Tab 4G

**Comment by zytzagoo** [comment]
Could you please run the test suite in the same environment and see how it behaves?

**Comment by mxdpeep** [comment]
I have switched to https://silktide.com/tools/cookie-consent/ https://github.com/mxdpeep/cookieconsent2

**Comment by webaddicto** [comment]
Works fine the latest version, I tested it here:
https://appetize.io/demo?device=nexus5&scale=100&orientation=portrait&osVersion=4.4

I attached a screenshot:
![android4](https://cloud.githubusercontent.com/assets/8770136/21182206/231d3830-c202-11e6-80d8-8b8e853b0826.png)
