### ISSUE TITLE
Could you help add git tag

### ISSUE THREAD

**Issue by kennynaoh** [dobarkod/cookie-banner#41]
Hello @zytzagoo  I am the member of cdnjs project. We want to host this library. Git tag can help us to know your release version, and we can auto-update the version when you have new release. Could you please help us add git tag. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/9956

**Comment by zytzagoo** [comment]
Hi @kennynaoh , I don't have commit/push access here, so can't really do much about it. Ping @senko.

**Comment by senko** [comment]
@kennynaoh awesome, would be great to be hosted on cdnjs!

I’ll be happy to tag the latest release; please let me know if there are any other things we could or should to to be a better cdnjs citizen.

@zytzagoo let me know if you’d want / accept edit/admin privs for the repo, you’re more active here than I am, so if you volounteer to shoulder the burden of (co)maintaining this officially, lemme know :-)

**Comment by zytzagoo** [comment]
@senko i'll help as much as I can, sure. I think I said as much already (yep, found it: https://github.com/dobarkod/cookie-banner/pull/35#issuecomment-162850521)

**Comment by senko** [comment]
@zytzagoo Sheesh I’m blind :-) Great, invited you as admin!

**Comment by kennynaoh** [comment]
Good to listen that. Please let me know if there is any update. Thanks @zytzagoo @senko

**Comment by zytzagoo** [comment]
@kennynaoh tag/release added. Minified js is not included in it though, is that ok?

BTW, does anyone know if github's "include binaries" thingy (when doing a release through github ui) allows treating .min.js as "binaries" and if the file can be placed in arbitrary location within the zip/tarball?

(don't have the minified version handy [and/or dev env] on this puter, so can't check myself until tomorrow)

**Comment by senko** [comment]
Looking at https://help.github.com/articles/creating-releases/ it doesn’t look as if it gives a lot of leeway with binaries upload

**Comment by zytzagoo** [comment]
Indeed. Might not matter much anyway: https://webdevlaw.uk/2017/01/10/cookie-law-reform-announcement/

**Comment by kennynaoh** [comment]
@zytzagoo It's fine not to add minified file. I can help minify it. Thanks!
I will add this ASAP.

**Comment by kennynaoh** [comment]
It's already on CDNJS https://cdnjs.com/libraries/cookie-banner. Thank guys!
