### ISSUE TITLE
.cookiebanner-close element missing

### ISSUE THREAD

**Issue by jonathanprehn** [dobarkod/cookie-banner#54]
On Iphone7, the default X (&#10006;) is not showing.

**Comment by zytzagoo** [comment]
Do you have a URL where the issue can be checked? Ideally a jsfiddle (or some such, where the issue is demonstrated in an isolated fashion to avoid conflicts with some other css/js code etc.)?

Can you run/open the tests/demo.html file on that device and confirm the issue?

**Comment by zytzagoo** [comment]
Seems to work fine even with 1.0.0 version from cdnjs as demonstrated here: https://jsfiddle.net/es5cj9af/
