### ISSUE TITLE
Styling option not working

### ISSUE THREAD

**Issue by jonathanprehn** [dobarkod/cookie-banner#55]
The option to style the close icon has no effect.

Option name: close-style

`
	<script type="text/javascript"
		id="cookiebanner"
		src="/scripts/cookiebanner.min.js"
		data-zindex="1000"
		data-moreinfo="/cookie-politik/"
		data-linkmsg="Få mere at vide"
		data-message="cookietext" data-close-style="padding-left:15px"
    data-close-text="X"
	></script>
`

**Comment by zytzagoo** [comment]
Which version are you using? Seems to work fine even with 1.0.0 version from cdnjs as demonstrated here: https://jsfiddle.net/es5cj9af/
