### ISSUE TITLE
Multi-line data-message

### ISSUE THREAD

**Issue by felipesanti** [dobarkod/cookie-banner#57]
Hi,
It would be great to have the possibility to add multi-line messages in the data-message field, e.g. 
Lorem ipsum\ndolor sit amet"
Thanks!

**Comment by zytzagoo** [comment]
Seems to work fine with using `<br>` in there instead of `\n`: https://jsfiddle.net/xb2yurLx/

Fiddle is using this markup:
```html
<script type="text/javascript" id="cookiebanner" src="https://cdnjs.cloudflare.com/ajax/libs/cookie-banner/1.0.0/cookiebanner.min.js" data-zindex="1000" data-moreinfo="/cookie-politik/" data-linkmsg="Få mere at vide" data-message="Some cookie text here<br>with new lines<br>weee!" data-close-style="padding-left:15px" data-close-text="X" ></script>
```

Which renders like this:
![fiddle-multiline-example-capture](https://cloud.githubusercontent.com/assets/46947/26247625/0cace074-3c9f-11e7-97cf-06f20fe01680.png)

**Comment by felipesanti** [comment]
@zytzagoo nice, thank you!
