### ISSUE TITLE
magnific-popup integration

### ISSUE THREAD

**Issue by fabiocaccamo** [dobarkod/cookie-banner#61]
Hi, 
thanks for this nice utilty.

I'm using `cookie-banner` in a project where I would like to show the **privacy policy** in a popup managed by [magnific-popup](http://dimsemenov.com/plugins/magnific-popup/), but the `"moreinfo"` option support only links. 

Any suggestion?

**Comment by zytzagoo** [comment]
Here's a really quick/crude demo to get you started: https://jsfiddle.net/81pyfhuc/

(clicking "I agree." should result in a crude modal popup appearing, with a dismiss link inside it).

You should pretty much be able to do whatever you want with it (with regards to magnific-popup integration), it's just a matter of targeting specific elements on the page and attaching proper behavior.

If you have any specific problems getting something working, please use a fiddle or similar to demonstrate what exactly you're trying to achieve (and what exactly isn't working).
