### ISSUE TITLE
Callbacks not working on dist/cookiebanner.min.js

### ISSUE THREAD

**Issue by zeeshangulzar** [dobarkod/cookie-banner#77]
Callbacks e.g. `onInserted` not seems to be working on minified Js file. But working fine on source(`js`) file. Kindly check.

**Comment by zeeshangulzar** [comment]
Yep, I just grab the latest zip from github. And testing callbacks and found out the issue. (Also `onInserted` works as expected but `onClosed` not calling somehow. ) By the way, thanks for looking into the Js minified issue.

**Comment by zytzagoo** [comment]
Minified version updated.

Can you share a bit more details about onClosed not working? There's a basic test in tests.js L:251 that confirms it's being called as expected in that case at least...

**Comment by zytzagoo** [comment]
Closing, please reopen or create a new issue if something is not right.
