### ISSUE TITLE
Does not show up in Firefox or Chrome

### ISSUE THREAD

**Issue by page6de** [dobarkod/cookie-banner#80]
It seems as the Cookie Banner does not show up in Firefox or Chrome (on Mac) anymore, neither in Safari on iOS. No "cookiebar: CookieAllowed" Cookie is set so far. Maybe you can take a look at that.

**Comment by zytzagoo** [comment]
https://github.com/dobarkod/cookie-banner/search?q=cookiebar&unscoped_q=cookiebar

I don't see that string ("cookiebar") anywhere in our codebase... Can you provide a jsfiddle (or something similar) demonstrating the issue you appear to be experiencing?

**Comment by page6de** [comment]
Oh! I'm so sorry!!! This is the totally wrong project!
Please delete this issue or mark it as solved.
This is so embarrasing, that I've picked the wrong repository.
Once again, I'm really sorry!
