### ISSUE TITLE
Allow hide "More Info" link

### ISSUE THREAD

**Issue by laurentmuller** [dobarkod/cookie-banner#81]
It's possible to add an option to hide the "More Info" link?

For example: `moreinfo-hide` - Hide more info link (default: `false`)

**Comment by zytzagoo** [comment]
Erm... anything's possible, just not sure if (yet another) option is really needed for this?

What's the motivation behind being able to hide it?
Is it a relatively common use-case?

Also, are we talking about hiding it visually (and perhaps you don't have control over the site's CSS), or "hide" in the sense that the entire link element is not added to the DOM at all?

For example, it's possible to build a cookie banner that doesn't have any links in it (if that's what you're after) by doing something like this:

https://codepen.io/anon/pen/MBMZLV

```
<script id="cookiebanner" src="https://cdn.jsdelivr.net/gh/dobarkod/cookie-banner@1/dist/cookiebanner.min.js" data-message="We use <a style='display:none;'>hidden</a> cookies and our privacy statement is great!" data-linkmsg="" data-moreinfo="false"></script>
```

**Comment by laurentmuller** [comment]
It' OK for me with your example. I can also use `CSS` to hide the link.
