### ISSUE TITLE
`expires` option doesn't work with Firefox.

### ISSUE THREAD

**Issue by fabiocaccamo** [dobarkod/cookie-banner#89]
Hi, 
I'm not setting the `expires` option because the default value `Infinity` is ok in my case.

I noticed that the cookie-banner shows from time to time after having agreed once, so I decided to set the `expires` option. 

Setting the option I noticed that the expiration date is always one week (I tried to set it using seconds and also explicit Date object).

Initially I though it was a problem of the option, but I tested the same code with Chrome and it works well, so it's a Firefox (v.106) issue.

**Comment by zytzagoo** [comment]
Hi, sorry for the delay, and sorry to have to say that it's kind of hard to give more concrete info without having/seeing/testing a minimal reproducible example somewhere.

I tried running the tests manually in latest Firefox on osx, nothing breaks there. But this doesn't really prove much (in and of itself).

Maybe we could come up with a test for this exact scenario and add it to the test suite, but first we'd probably want to figure out what exactly is failing in the first place? Is it Cookies.set(), or Cookies.get()? Or neither and it's just a "duration" issue? Why only 7 days? Very strange.

Could you provide a minimal reproducible example somewhere online (or just code/options for it) that demonstrates the exact issue you're having?

**Comment by fabiocaccamo** [comment]
Hi, thank you for the feedback.
This is the code I run:

```javascript
let options = {
    "message": "Our website uses cookies ...",
    "linkmsg": "Cookie Policy",
    "moreinfo": "/cookie-policy/",
    "cookie": "cookie-consent",
    "cookie-secure": (window.location.protocol === 'https:' ? true : false),
    "close-text": "&#10005;"
};
this._cookieBanner = new Cookiebanner(options);
this._cookieBanner.run();
```

As you can see I don't set the expiration date. 

I now deleted the cookie from both Firefox and Chrome, then:

I open the website with Firefox, I accept the cookie-policy and this is the cookie expiration date:

> <img width="603" alt="Screenshot 2022-11-15 at 15 25 43" src="https://user-images.githubusercontent.com/1035294/201943846-37b68414-9439-46bf-a536-7c837e8a7e54.png">

I open the website with Chrome, I accept the cookie-policy and this is the cookie expiration date:

> <img width="404" alt="Screenshot 2022-11-15 at 15 27 21" src="https://user-images.githubusercontent.com/1035294/201944193-08ab885a-a728-438f-bafb-04afbaaffda2.png">

This can't be an implementation problem.

**Comment by zytzagoo** [comment]
I cannot replicate :/

For me, in Firefox (107, osx), running either the test suite (via file:///) or serving up a blank demo page via http, I get the "expected" expiry dates:

<img width="1060" alt="Screenshot 2022-11-15 at 17 15 14" src="https://user-images.githubusercontent.com/46947/201975219-8d0f43bd-0b2c-4fe7-a26d-38c35601dcbf.png">

<img width="1334" alt="Screenshot 2022-11-15 at 17 35 15" src="https://user-images.githubusercontent.com/46947/201975172-e0b4c468-7305-4f9f-8773-76e08a63b3eb.png">

Not sure what to do in order to prove the default/Infinity expiry in the tests suite though (since there is no way to get that data directly out of document.cookie)

**Comment by fabiocaccamo** [comment]
Incredibile, I try to replicate it in smaller scale.

**Comment by zytzagoo** [comment]
Any luck finding out what's going on exactly?

**Comment by fabiocaccamo** [comment]
Sorry for the silence, I will isolate a test this week.

**Comment by fabiocaccamo** [comment]
@zytzagoo here the minimal test:

## HTML 
`cookiebanner.html` file with the following content:
```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>cookiebanner</title>
    </head>
    <body>
        <script type="text/javascript" src="cookiebanner.js"></script>
        <script type="text/javascript">
            let cookieBanner = new Cookiebanner({
                "message": "Our website uses cookies ...,",
                "linkmsg": "Cookie Policy",
                "moreinfo": "/cookie-policy.html",
                "cookie": "test-cookiebanner",
                "cookie-secure": (window.location.protocol === 'https:' ? true : false),
                "close-text": "&#10005;"
            });
            cookieBanner.run();
        </script>
    </body>
</html>
```

## JS
`cookiebanner.js` file taken from [master](https://raw.githubusercontent.com/dobarkod/cookie-banner/master/src/cookiebanner.js)

## COOKIE
This is the result cookie set on `macOS Monterey 12.2.1` / `Firefox 107.0.1`:

<img width="598" alt="Screenshot 2022-12-14 at 14 20 51" src="https://user-images.githubusercontent.com/1035294/207606218-6fdd1b0e-56b6-482a-ad2e-b782765c71e5.png">

As you can see the default "infinite" expiration date doesn't work, it is set to one week.

**Comment by zytzagoo** [comment]
For me it behaves as expected, Firefox 107.0.0, macOS High Sierra (10.13.6), here are the screenshots:

![Screen Shot 2022-12-15 at 12 34 20](https://user-images.githubusercontent.com/46947/207850274-27372eef-3eff-4025-b2df-b1792d8a1b85.jpg)

![Screen Shot 2022-12-15 at 12 34 38](https://user-images.githubusercontent.com/46947/207850298-9a7e7970-06a5-4526-97fc-5b84571d8159.jpg)

![Screen Shot 2022-12-15 at 12 34 53](https://user-images.githubusercontent.com/46947/207850324-7a27025e-edff-4d74-b0cc-9bc7383c99d9.jpg)

**Comment by fabiocaccamo** [comment]
Thank you for your feedback. 
I isolated the problem, it's caused by a browser extension. I try now to isolate also the extension that causes that.

**Comment by fabiocaccamo** [comment]
These the extensions I'm using, not too many and pretty popular:

<img width="618" alt="Screenshot 2022-12-15 at 13 05 30" src="https://user-images.githubusercontent.com/1035294/207855128-344280a0-8a68-48d5-99ca-ad971ef71e7e.png">

**Comment by zytzagoo** [comment]
Perhaps something in your firefox profile (or install) is wonky -- did you maybe try a new/fresh profile (and/or [re]install) and see if the issue persists there? 

I have uBlock Origin as well, so can't be that. The only other suspect could be DuckDuckGo Privacy Essentials maybe? (if it's really caused by an extension at all)

**Comment by fabiocaccamo** [comment]
I confirm it, I don't know why, but it's caused by the "DuckDuckGo Privacy Essentials" extension.

**Comment by zytzagoo** [comment]
It's a feature, described here: https://help.duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/ -- search for '7-day' (1st party cookie protection)

**Comment by fabiocaccamo** [comment]
ohhh didn't know that, thank you very much!
